export const faqData = [
    { title: 'What is surrogacy, and how does it work?', summary: 'Surrogacy refers to the process in which a woman, known as the surrogate, carries and delivers a child for intended parents who may be unable to conceive or carry a pregnancy themselves. The surrogacy process involves various stages, including medical screenings, legal agreements, and fertility treatments.' },
    { title: 'Is surrogacy the right choice for me?', summary: 'Deciding to pursue surrogacy is a deeply personal choice. Intended parents should consider their emotional readiness, financial capability, and support network. Surrogates should assess their physical and emotional health, as well as their willingness to carry a pregnancy for someone else.' },
    { title: 'What are the different types of surrogacy?', summary: 'There are two primary types of surrogacy: gestational and traditional. Gestational surrogacy involves using the surrogates uterus to carry an embryo created from the intended parents or donors genetic material.Traditional surrogacy, on the other hand, uses the surrogates own eggs, making her genetically related to the child.' },
    { title: 'What is the difference between independent surrogacy and agency-supported surrogacy?', summary: 'Independent surrogacy refers to a surrogacy arrangement without the involvement of a surrogacy agency. Intended parents and surrogates directly connect and work through the process together. Agency-supported surrogacy involves receiving professional assistance from a surrogacy agency throughout the journey.' },
    { title: 'What are the legal aspects of surrogacy?', summary: 'Surrogacy laws vary significantly depending on the country or state. It is essential to understand the legal implications and requirements regarding the surrogacy process in your region, including parental rights, financial agreements, and surrogacy contracts.' },
    { title: 'How do I find a surrogate or intended parents independently?', summary: 'Finding a suitable match independently involves networking, engaging with surrogacy communities, and utilizing online platforms designed to connect intended parents and surrogates. Experienced surrogacy attorneys can also provide valuable guidance via legal consultations.' },
    { title: 'Is compensation involved in surrogacy?', summary: 'Compensation is determined by the type of surrogacy and applicable laws. In commercial surrogacy, the surrogate receives financial compensation beyond medical expenses. In contrast, altruistic surrogates (i.e., women who volunteer to carry a pregnancy to term for intended parents) only receive compensation for eligible expenses.' },
    { title: 'What are the emotional and psychological considerations regarding surrogacy?', summary: 'Surrogacy is an emotionally charged journey for all parties involved. Intended parents and surrogates should prepare themselves for potential emotional challenges and consider seeking help from counselors or support groups to navigate these feelings.' },
    { title: 'What medical screenings are involved in the surrogacy process?', summary: 'Both surrogates and egg donors (if used) typically undergo thorough medical and psychological screenings to ensure their suitability for the process and to address any potential health risks.' },
    { title: 'How can FindSurrogate.com support me in my surrogacy journey?', summary: 'FindSurrogate.com is committed to providing comprehensive resources, expert guidance, and a supportive community for intended parents and surrogates alike. Our platform aims to streamline the surrogacy process, making it a positive and fulfilling experience for everyone ' },
]